ALTER TABLE "WarehouseItem" ADD COLUMN "purchasePrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WarehouseItem" ADD COLUMN "purchaseGram" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "WarehouseItem" ADD COLUMN "pricePerGram" DOUBLE PRECISION NOT NULL DEFAULT 0;
